# -*- coding: utf-8 -*-
"""DASHBOARD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-ONaFssYaw-r2TxsTBMaR9gBb3gr5_A
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import plotly.express as px
from babel.numbers import format_currency
sns.set(style='dark')

# Membaca data dari file CSV
data = pd.read_csv('all_data.csv')

st.header('Bike Sharing Dashboard :sparkles:')

# Menampilkan data dalam bentuk tabel
st.subheader('Data')
st.write(data)

# Menampilkan tren penggunaan sepeda dari waktu ke waktu
st.subheader('Tren Penggunaan Sepeda dari Waktu ke Waktu')

# Menghitung jumlah pengguna sepeda per tanggal
df_daily = data.groupby('dteday')['cnt_x'].sum().reset_index()

# Membuat plot tren penggunaan sepeda dari waktu ke waktu
fig = px.line(df_daily, x='dteday', y='cnt_x', title='Tren Penggunaan Sepeda dari Waktu ke Waktu')
fig.update_xaxes(title='Tanggal')
fig.update_yaxes(title='Jumlah Pengguna Sepeda')
st.plotly_chart(fig)

# Menampilkan perbedaan dalam pola penggunaan sepeda antara hari kerja dan akhir pekan
st.subheader('Perbedaan Pola Penggunaan Sepeda antara Hari Kerja dan Akhir Pekan')

# Mengelompokkan data berdasarkan hari kerja dan akhir pekan
weekday_data = data[data['workingday_x'] == 1]
weekend_data = data[data['workingday_x'] == 0]

# Menghitung rata-rata penggunaan sepeda per hari kerja dan akhir pekan
weekday_avg = weekday_data['cnt_x'].mean()
weekend_avg = weekend_data['cnt_x'].mean()

# Membuat plot perbandingan penggunaan sepeda antara hari kerja dan akhir pekan
fig, ax = plt.subplots(figsize=(8, 6))
ax.bar(['Hari Kerja', 'Akhir Pekan'], [weekday_avg, weekend_avg], color=['red', 'pink'])
ax.set_xlabel('Hari')
ax.set_ylabel('Rata-rata Jumlah Pengguna Sepeda')
ax.set_title('Perbandingan Penggunaan Sepeda antara Hari Kerja dan Akhir Pekan')
st.pyplot(fig)